site_name: Pandunia
site_url: http://www.pandunia.info/espani
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../portugali
site_dir: ../../html/portugali
theme: readthedocs
nav:
    - Inicio: 'index.md'
    - 'Ortografía': abc.md
    - 'Dicionarios':
        - 'Pandunia-Português': pandunia-portugali.md
        - 'Português-Pandunia': portugali-pandunia.md
        - 'Dicionario etimologico': leksaslia.md

