site_name: Pandunia
site_url: http://www.pandunia.info/suomi
repo_url: https://github.com/barumau/pandunia/
site_author: Risto Kupsala
docs_dir: ../../suomi
site_dir: ../../html/suomi
theme:
  name: cerulean
  language: fi
plugins:
    - search:
        lang: fi
nav:
    - Kotisivu: 'index.md'
    - 'Tietoa':
        - 'Maailman yhteyskieli': dunia_baxe.md
        - 'Kysymyksiä & vastauksia': eske_i_jawabe.md
    - 'Pandunian perusteet ja rakenne':
        - 'Perussäännöt': 100_bazi_kanune.md
        - 'Yleismaailmallinen sanasto': 101_dunia_loge.md
        - 'Ääntäminen': 102_ABC.md
        - 'Substantiivit': 104_namloge.md
        - 'Adjektiivit': 105_sifloge.md
        - 'Adverbit': 106_modologe.md
        - 'Numeraalit': 107_numloge.md
        - 'Pronominit': 108_visloge.md
        - 'Verbit': 109_karloge.md
        - 'Lauserakenteita': 110_jumle.md
    - 'Oppitunteja':
        - 'Lauseita': fraze.md
        - 'Kurssi': darse.md
    - 'Sanasto':
        - 'Pandunia-suomi': pandunia-suomi.md
        - 'Suomi-pandunia': suomi-pandunia.md
        - 'Alkuperäsanasto': leksaslia.md

